version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - clettenberg
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - clettenberg
  ignore:
  - dependency-name: "@rails/webpacker"
    versions:
    - 5.2.2
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
    - 3.11.0
  - dependency-name: browserslist
    versions:
    - 4.16.4
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.13
