version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: travel-test-user
          RAILS_ENV: test
          MAPBOX_TOKEN: replace-me
      - image: circleci/postgres:9.6-alpine-postgis
        environment:
          POSTGRES_USER: travel-test-user
          POSTGRES_DB: travel_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install postgresql-client -y

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - travel-bundle-{{ checksum "Gemfile.lock" }}
            - travel-bundle-

      - run:
          name: Bundle Install
          command: bundle check || bundle install


      - save_cache:
          key: travel-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - travel-yarn-{{ checksum "yarn.lock" }}
            - travel-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn


      - save_cache:
          key: travel-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:structure:load --trace

      - run:
          name: Compile Webpacker Assets
          command: MAPBOX_TOKEN=replace-me bin/rails webpacker:compile

      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - type: shell
        command: yarn test

      - store_test_results:
          path: test_results
