version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run: echo "A first hello"
deployment:
  staging:
    branch: master
    heroku:
      appname: clettenberg-travel-staging
